# model
model_name_or_path: /data2/machao/qwen/Qwen2.5-7B-Instruct

# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# ddp
ddp_timeout: 180000000

# dataset
dataset: test_sft
template: qwen
cutoff_len: 1024
max_samples: 500000
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: /data2/machao/qwen/qwenft/Qwen2.5-7B-Instruct
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 24
gradient_accumulation_steps: 2
learning_rate: 0.0005
num_train_epochs: 20.0
lr_scheduler_type: cosine
# warmup_steps: 0.1
fp16: true
lora_rank: 64
lora_alpha: 32
lora_dropout: 0.05

# eval
per_device_eval_batch_size: 9
evaluation_strategy: steps
eval_steps: 500
